/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.instamint.services;

import com.instamint.services.mint.algo.AlgoMintConsumer;
import com.instamint.services.mint.eth.EthMintConsumer;

public class App {
    public void start() {
        new Thread(new EthMintConsumer()).start();
        new Thread(new AlgoMintConsumer()).start();
    }

    public static void main(String[] args) throws Exception {
        new App().start();
    }
}
