/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.instamint.services.mint.eth;

import io.github.cdimascio.dotenv.Dotenv;

import java.sql.*;

public class App {
    public void start() {
        new Thread(new Consumer()).start();
    }

    public static void main(String[] args) throws Exception {
        new App().start();
    }
}
