/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.instamint.services.mint.eth;

import com.instamint.services.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
